### ISSUE TITLE
Possible mistakes in command example outputs.

### ISSUE THREAD

**Issue by cruse123** [codeHaiku22/Btrfs-Guide#1]
In the last code block of section **[Recovering a Snapshot](https://github.com/codeHaiku22/Btrfs-Guide/tree/main#recovering-a-snapshot)**, after shifting the default mount-point back and forth, the subvolume `snapshots-ro` should not be here as it is *NOT* demonstrated until the next section **[Creating a Read-Only Snapshot for Transmission](https://github.com/codeHaiku22/Btrfs-Guide/tree/main?tab=readme-ov-file#creating-a-read-only-snapshot-for-transmission)**. So I suppose there are possible mistakes in the command outputs of `ls -R *`. 

The correct one may be:

```
$ ls -R *
notes:
note1.txt  note2.txt  note3.txt

snapshots:
files  notes

snapshots/files:
file1.txt  file2.txt  file3.txt

snapshots/notes:
note1.txt  note2.txt  note3.txt
```

**Comment by codeHaiku22** [comment]
Thanks so much for catching this error.  I will fix the output accordingly for the `ls -R *` command.
